### ISSUE TITLE
使用enre_java_1.2.3解析安卓系统报错

### ISSUE THREAD

**Issue by shang-jw** [xjtu-enre/ENRE-java#46]
Exception in thread "main" java.lang.OutOfMemoryError: UTF16 String size is 1207959550, should be less than 1073741823

根据Badger的这个回答(https://discuss.elastic.co/t/out-of-memory-error-and-duplicate-rows/321932)
Is it possible that one of your documents is over 1 GB? A few years ago the maximum string size in Java was [reduced](https://bugs.openjdk.org/browse/JDK-8190429) from 2 GB (because each UTF-16 character uses 2 bytes and it uses a 32-bit string length) to 1 GB (a side-effect of compact strings which are byte arrays rather than char arrays).
可能原因是输出文件大小超过1G导致的报错。

增加参数-s (slim版本输出后，文件大小为800+M，能够输出）

**Comment by Lynn-Dai** [comment]
The OOM Error is too hard to deal with, you can increase your heap memory using command or change to run on VM..
